version: '3.8'

services:
  app:
    container_name: quantization_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    command: tail -f /dev/null
    # add GPU support if available
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

